/**
 * Données de démo pour les classements de jeux
 * Contient 50 joueurs fictifs avec des scores variés
 * Utilisé pour générer un classement démo
 */
export const DEMO_PLAYERS = [
  { name: "AlexGamer", points: 2847, country: "FR" },
  { name: "MariePro", points: 2654, country: "CA" },
  { name: "PierreMaster", points: 2489, country: "FR" },
  { name: "SophieChamp", points: 2341, country: "BE" },
  { name: "LucasStar", points: 2198, country: "CH" },
  { name: "EmmaQueen", points: 2056, country: "GB" },
  { name: "ThomasElite", points: 1923, country: "DE" },
  { name: "JuliePro", points: 1789, country: "FR" },
  { name: "MaxGaming", points: 1654, country: "US" },
  { name: "SarahWinner", points: 1521, country: "AU" },
  { name: "DavidChamp", points: 1387, country: "ES" },
  { name: "LisaElite", points: 1254, country: "IT" },
  { name: "PaulMaster", points: 1121, country: "NL" },
  { name: "AnnaPro", points: 987, country: "SE" },
  { name: "KevinStar", points: 854, country: "NO" },
  { name: "ClaraWinner", points: 721, country: "DK" },
  { name: "MarcElite", points: 588, country: "FI" },
  { name: "NinaChamp", points: 455, country: "PL" },
  { name: "LeoGaming", points: 322, country: "CZ" },
  { name: "ZoePro", points: 289, country: "AT" },
  { name: "HugoStar", points: 256, country: "HU" },
  { name: "EvaWinner", points: 223, country: "RO" },
  { name: "RaphaelElite", points: 190, country: "BG" },
  { name: "CamilleChamp", points: 157, country: "HR" },
  { name: "AntoineGaming", points: 124, country: "SI" },
  { name: "LouisePro", points: 91, country: "SK" },
  { name: "BaptisteStar", points: 78, country: "EE" },
  { name: "ChloeWinner", points: 65, country: "LV" },
  { name: "ArthurElite", points: 52, country: "LT" },
  { name: "JadeChamp", points: 39, country: "MT" },
  { name: "NathanGaming", points: 26, country: "CY" },
  { name: "AlicePro", points: 23, country: "LU" },
  { name: "VictorStar", points: 20, country: "IE" },
  { name: "InesWinner", points: 17, country: "PT" },
  { name: "RomainElite", points: 14, country: "GR" },
  { name: "LolaChamp", points: 11, country: "HR" },
  { name: "GabrielGaming", points: 8, country: "SI" },
  { name: "MayaPro", points: 5, country: "SK" },
  { name: "LouisStar", points: 2, country: "EE" },
  { name: "ElenaWinner", points: 1, country: "LV" },
  { name: "FelixChamp", points: 0, country: "IS" },
  { name: "MiaGaming", points: 0, country: "AD" },
  { name: "OscarPro", points: 0, country: "MC" },
  { name: "IsabellaStar", points: 0, country: "LI" },
  { name: "LiamWinner", points: 0, country: "SM" },
  { name: "AvaElite", points: 0, country: "VA" },
  { name: "NoahChamp", points: 0, country: "KZ" },
  { name: "EmmaGaming", points: 0, country: "UZ" },
  { name: "WilliamPro", points: 0, country: "KG" },
  { name: "OliviaStar", points: 0, country: "TJ" },
];
